### ISSUE TITLE
.NET Standard?

### ISSUE THREAD

**Issue by mmo-mikhail** [KevinDockx/JsonPatch#103]
Can it be updated to the latest .netstandard please? @KevinDockx  Or it's no longer supported?

**Comment by KevinDockx** [comment]
That shouldn't be too hard, but you might as well use https://www.nuget.org/packages/Microsoft.AspNetCore.JsonPatch/ if you're running on a platform that supports NetStandard2.0.  I ported Marvin.JsonPatch to ASP.NET Core a few years ago, and it has evolved as a part of ASP.NET Core since Core 1.x.    Is there a reason why you'd prefer to use Marvin.JsonPatch instead of Microsoft.AspNetCore.JsonPatch?

**Comment by KevinDockx** [comment]
Here you go: https://www.nuget.org/packages/Marvin.JsonPatch/
