### ISSUE TITLE
Expose ExpressionHelpers.GetPath

### ISSUE THREAD

**Issue by borbzz** [KevinDockx/JsonPatch#48]
Would it be possible for you to expose the expression helpers extension method `GetPath<T, TProp>`? Right now it's in an `internal` static class.  It would be useful to use LINQ to compare paths against ones specified in an in incoming PATCH request?  Thanks!

**Comment by KevinDockx** [comment]
Do you happen to have a use case for wanting to compare those? 

I'm quite hesistant to exposing features that were intended for internal use, but I'm open for suggestions if there's a good reason for opening this up (well, you can of course just copy the code into your own project :)).

**Comment by dario-hd** [comment]
@KevinDockx well, I think it would be nice to be able to reuse such methods. For example, I just created a new Adapter which implement the IObjectAdapter<T> interface and I would like to reuse the methods in the PropertyHelper class. Otherwise I would end up rewriting the same code or I would need to fork the repo. What do you think?

**Comment by KevinDockx** [comment]
Sorry for the delay in replying.  Sounds like a good use case to me.  Change has been committed, will be in the next release :)
